# Generated by Django 3.2.21 on 2024-07-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(default='', max_length=50)),
                ('paymnt_sts', models.CharField(default='', max_length=40)),
                ('date', models.CharField(default='', max_length=30)),
                ('OWNSERVICES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.own_services')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
