# Generated by Django 3.2.21 on 2024-07-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='OWNSERVICES',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.own_services'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
