# Generated by Django 3.2.21 on 2024-07-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240722_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='OWNSERVICES',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.own_services'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='bankname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='paymnt_sts',
            field=models.CharField(max_length=40),
        ),
    ]
